name: dx
description: Generates .dart files from .dx files.
version: 0.0.1
homepage: https://github.com/yjbanov
author: Yegor Jbanov <yjbanov@google.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  charcode: ^1.1.1
  meta: ^1.1.1
  path: ^1.4.1
  string_scanner: ^1.0.2

dev_dependencies:
  test: ^0.12.0
